### ISSUE TITLE
Doesn't work at all for me

### ISSUE THREAD

**Issue by EdFenner** [jakethashi/vscode-angular2-emmet#1]
I keep trying to get this to work and get nowhere. I uninstalled every other extension and still no go. All I get after putting some simple emmet like ul>li and hitting tab, is a tab after.

**Comment by jakethashi** [comment]
Basically the extension should work inside template's Component decorator. So your code may look like this example

```
@Component({
  selector: 'my-app',
  template: 'ul>li'
})
```

If you hit tab key after emmet expression the abbreviation should be replace into HTML.

**Comment by EdFenner** [comment]
Thanks for the comment. I had tried it in a Typescript file but not inside the decorator - I did not see that was a requirement. Doing that, your example above almost works. If I use that, it does expand but only to:
<ul><li></li></ul>. 
I also tried the examples from the install page. It does not create new lines or indent.

**Comment by jakethashi** [comment]
Can you write down steps to reproduce that?

**Comment by Deviad** [comment]
It does not work for me either on VSCode 1.5.3

**Comment by jakethashi** [comment]
It is working also in 1.5.3. Add more detail about the issue. Thx.
