### ISSUE TITLE
Emmet seems not working multiline

### ISSUE THREAD

**Issue by DavidBabel** [jakethashi/vscode-angular2-emmet#2]
Hi,

When i try to use emmet in my typescript files, it does work but only inline and not multiline.

VSCode: 1.7.1
OS : MacOS Sierra

Thanks

**Comment by jakethashi** [comment]
Can you provide the code example which doesn't work, thanks.

**Comment by DavidBabel** [comment]
Oww i can't reproduce this again :( I will bump this issue if it append again, sorry
