### ISSUE TITLE
Breaks snippet flow with Angular2 typescript snippets

### ISSUE THREAD

**Issue by thekalinga** [jakethashi/vscode-angular2-emmet#3]
1. Insert `ng2-component` snippet from [Angular2 typescript snippets](https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular2)
2. Press tab
3. Instead of moving to the next tab location to the next edit point of the snippet, this plugin hijacks that action & inserts a tab, which is not correct

The plugin should identify whether the user is in the process of inserting a snippet/editing code normally.

If in snippet edit mode, this plugin should let the editor do its job. Else, try interpreting the preceding string as Emmet

**Comment by jakethashi** [comment]
Thanks for reporting this issue. The bug is well known issue, because I am not able to insert emmet result as snippet and thats why I have to handle tab key by my own. As a side effect this may break tab markers for other snippets and so on. I'll try to fix it asap.

**Comment by lawrencecushman** [comment]
I think I'm seeing a similar issue where tab behaviour is hijacked within regular ts code, not just snippet completion. It's preventing using tab for intellisense completions. 

1. Start typing a reference to any declared object. eg... `this.eventSer` where "eventService" pops up as an intellisense option. 
2. Hitting tab should complete the member name.

After installing this plugin tab to complete intellisense behaviour is gone. Hitting enter still to complete still works.

**Comment by jakethashi** [comment]
it should be fixed now
