### ISSUE TITLE
Expansion not using entire Emmet abbreviation

### ISSUE THREAD

**Issue by vdvman1** [jakethashi/vscode-angular2-emmet#6]
When trying to expand an Emmet abbreviation it does not expand the whole thing.
It appears to break any time +,#, {}, or . are in the abbreviation

Example with not working:
![incomplete-completion](https://cloud.githubusercontent.com/assets/2172023/22452417/c77f3886-e7ca-11e6-973a-76fcc5ffd4a7.gif)

Working:
![working-completion](https://cloud.githubusercontent.com/assets/2172023/22452470/3e943476-e7cb-11e6-802a-489e42051caa.gif)

**Comment by jakethashi** [comment]
The issue has been fixed in version 2.0.0.
