### ISSUE TITLE
breaks typescript's autocomplete

### ISSUE THREAD

**Issue by johnpapa** [jakethashi/vscode-angular2-emmet#7]
![2017-05-25_19-19-36](https://cloud.githubusercontent.com/assets/1202528/26474487/4cb3110e-417f-11e7-9bfe-e0c90326051f.gif)

**Comment by failpunk** [comment]
@jakethashi maybe try contacting the VS Code team about the tab bubbling.  This is a pretty awesome plugin otherwise.

**Comment by jakethashi** [comment]
@failpunk Tanks for the tip, I'll gona kill this bug soon or die :) I have already created sort of fix but it dosn't solve the issue by 100%. Let's hope it will be solve soon.

@johnpapa Thanks for reporting the issue, it's all about handling the tab-key event, inside vscode there isn't such API which would provide declarative way how to catch the key without affecting snippet or other functionality (at least I'm not aware it). I'll try to do my best to solve it soon.

**Comment by johnpapa** [comment]
adding @chrisdias and @seanmcbreen from VS Code

**Comment by chrisdias** [comment]
@johnpapa @jakethashi is this a new issue with the 1.13 release?

**Comment by jakethashi** [comment]
Eventually I fixed the issue by myself, thanks for all comments.

**Comment by johnpapa** [comment]
Can you test this with angular essentials? if it works and doesnt break as shown above, i'll add it back.

**Comment by jakethashi** [comment]
ok, I'll test it soon.

**Comment by jakethashi** [comment]
Hi John. I have test it with angular essentials and it works as it should. There are no issue wich would prevent to use it.
